var h="I am studying javascript ";
let n="King";
const k="Little ";
alert(h);
alert("the name is "+k + n);
console.log(h);
console.log(h + k);
let age=45;
let isage="True";
let trophy=null;
trophy="l90@";
